// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DynamicItemStateMes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from DynamicItemStateMes.proto</summary>
  public static partial class DynamicItemStateMesReflection {

    #region Descriptor
    /// <summary>File descriptor for DynamicItemStateMes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DynamicItemStateMesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlEeW5hbWljSXRlbVN0YXRlTWVzLnByb3RvEgdNZXNzYWdlGhpEeW5hbWlj",
            "U2NlbmVJdGVtVHlwZS5wcm90byLeAQoTRHluYW1pY0l0ZW1TdGF0ZU1lcxIV",
            "Cg1keW5hbWljSXRlbUlkGAEgASgFEkQKCXN0YXRlVHlwZRgCIAEoDjIxLk1l",
            "c3NhZ2UuRHluYW1pY0l0ZW1TdGF0ZU1lcy5EeW5hbWljSXRlbVN0YXRlVHlw",
            "ZRIvCghpdGVtVHlwZRgDIAEoDjIdLk1lc3NhZ2UuRHluYW1pY1NjZW5lSXRl",
            "bVR5cGUiOQoURHluYW1pY0l0ZW1TdGF0ZVR5cGUSCAoETm9uZRAAEgoKBkNy",
            "ZWF0ZRABEgsKB0Rlc3Ryb3kQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.DynamicSceneItemTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.DynamicItemStateMes), global::Message.DynamicItemStateMes.Parser, new[]{ "DynamicItemId", "StateType", "ItemType" }, null, new[]{ typeof(global::Message.DynamicItemStateMes.Types.DynamicItemStateType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DynamicItemStateMes : pb::IMessage<DynamicItemStateMes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DynamicItemStateMes> _parser = new pb::MessageParser<DynamicItemStateMes>(() => new DynamicItemStateMes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DynamicItemStateMes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.DynamicItemStateMesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicItemStateMes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicItemStateMes(DynamicItemStateMes other) : this() {
      dynamicItemId_ = other.dynamicItemId_;
      stateType_ = other.stateType_;
      itemType_ = other.itemType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicItemStateMes Clone() {
      return new DynamicItemStateMes(this);
    }

    /// <summary>Field number for the "dynamicItemId" field.</summary>
    public const int DynamicItemIdFieldNumber = 1;
    private int dynamicItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DynamicItemId {
      get { return dynamicItemId_; }
      set {
        dynamicItemId_ = value;
      }
    }

    /// <summary>Field number for the "stateType" field.</summary>
    public const int StateTypeFieldNumber = 2;
    private global::Message.DynamicItemStateMes.Types.DynamicItemStateType stateType_ = global::Message.DynamicItemStateMes.Types.DynamicItemStateType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.DynamicItemStateMes.Types.DynamicItemStateType StateType {
      get { return stateType_; }
      set {
        stateType_ = value;
      }
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 3;
    private global::Message.DynamicSceneItemType itemType_ = global::Message.DynamicSceneItemType.ItemNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.DynamicSceneItemType ItemType {
      get { return itemType_; }
      set {
        itemType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DynamicItemStateMes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DynamicItemStateMes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DynamicItemId != other.DynamicItemId) return false;
      if (StateType != other.StateType) return false;
      if (ItemType != other.ItemType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DynamicItemId != 0) hash ^= DynamicItemId.GetHashCode();
      if (StateType != global::Message.DynamicItemStateMes.Types.DynamicItemStateType.None) hash ^= StateType.GetHashCode();
      if (ItemType != global::Message.DynamicSceneItemType.ItemNone) hash ^= ItemType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DynamicItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DynamicItemId);
      }
      if (StateType != global::Message.DynamicItemStateMes.Types.DynamicItemStateType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) StateType);
      }
      if (ItemType != global::Message.DynamicSceneItemType.ItemNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ItemType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DynamicItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DynamicItemId);
      }
      if (StateType != global::Message.DynamicItemStateMes.Types.DynamicItemStateType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) StateType);
      }
      if (ItemType != global::Message.DynamicSceneItemType.ItemNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ItemType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DynamicItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DynamicItemId);
      }
      if (StateType != global::Message.DynamicItemStateMes.Types.DynamicItemStateType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StateType);
      }
      if (ItemType != global::Message.DynamicSceneItemType.ItemNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ItemType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DynamicItemStateMes other) {
      if (other == null) {
        return;
      }
      if (other.DynamicItemId != 0) {
        DynamicItemId = other.DynamicItemId;
      }
      if (other.StateType != global::Message.DynamicItemStateMes.Types.DynamicItemStateType.None) {
        StateType = other.StateType;
      }
      if (other.ItemType != global::Message.DynamicSceneItemType.ItemNone) {
        ItemType = other.ItemType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DynamicItemId = input.ReadInt32();
            break;
          }
          case 16: {
            StateType = (global::Message.DynamicItemStateMes.Types.DynamicItemStateType) input.ReadEnum();
            break;
          }
          case 24: {
            ItemType = (global::Message.DynamicSceneItemType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DynamicItemId = input.ReadInt32();
            break;
          }
          case 16: {
            StateType = (global::Message.DynamicItemStateMes.Types.DynamicItemStateType) input.ReadEnum();
            break;
          }
          case 24: {
            ItemType = (global::Message.DynamicSceneItemType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the DynamicItemStateMes message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum DynamicItemStateType {
        [pbr::OriginalName("None")] None = 0,
        [pbr::OriginalName("Create")] Create = 1,
        [pbr::OriginalName("Destroy")] Destroy = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
