// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DynamicSceneItemType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from DynamicSceneItemType.proto</summary>
  public static partial class DynamicSceneItemTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for DynamicSceneItemType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DynamicSceneItemTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpEeW5hbWljU2NlbmVJdGVtVHlwZS5wcm90bxIHTWVzc2FnZSpBChREeW5h",
            "bWljU2NlbmVJdGVtVHlwZRIMCghJdGVtTm9uZRAAEgsKB0dyZW5hZGUQARIO",
            "CgpHcmVuYWRlRXhwEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Message.DynamicSceneItemType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum DynamicSceneItemType {
    [pbr::OriginalName("ItemNone")] ItemNone = 0,
    [pbr::OriginalName("Grenade")] Grenade = 1,
    [pbr::OriginalName("GrenadeExp")] GrenadeExp = 2,
  }

  #endregion

}

#endregion Designer generated code
