// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WallShootHitMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from WallShootHitMessage.proto</summary>
  public static partial class WallShootHitMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for WallShootHitMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WallShootHitMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlXYWxsU2hvb3RIaXRNZXNzYWdlLnByb3RvEgdNZXNzYWdlGhRWZWN0b3Iz",
            "TWVzc2FnZS5wcm90byKJAQoTV2FsbFNob290SGl0TWVzc2FnZRIOCgZ3YWxs",
            "SWQYASABKAUSJwoGb3JpZ2luGAIgASgLMhcuTWVzc2FnZS5WZWN0b3IzTWVz",
            "c2FnZRIkCgNkaXIYAyABKAsyFy5NZXNzYWdlLlZlY3RvcjNNZXNzYWdlEhMK",
            "C2VsZW1lbnRUeXBlGAQgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.Vector3MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.WallShootHitMessage), global::Message.WallShootHitMessage.Parser, new[]{ "WallId", "Origin", "Dir", "ElementType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 墙被击中，S -> C
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WallShootHitMessage : pb::IMessage<WallShootHitMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WallShootHitMessage> _parser = new pb::MessageParser<WallShootHitMessage>(() => new WallShootHitMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WallShootHitMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.WallShootHitMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WallShootHitMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WallShootHitMessage(WallShootHitMessage other) : this() {
      wallId_ = other.wallId_;
      origin_ = other.origin_ != null ? other.origin_.Clone() : null;
      dir_ = other.dir_ != null ? other.dir_.Clone() : null;
      elementType_ = other.elementType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WallShootHitMessage Clone() {
      return new WallShootHitMessage(this);
    }

    /// <summary>Field number for the "wallId" field.</summary>
    public const int WallIdFieldNumber = 1;
    private int wallId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WallId {
      get { return wallId_; }
      set {
        wallId_ = value;
      }
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 2;
    private global::Message.Vector3Message origin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.Vector3Message Origin {
      get { return origin_; }
      set {
        origin_ = value;
      }
    }

    /// <summary>Field number for the "dir" field.</summary>
    public const int DirFieldNumber = 3;
    private global::Message.Vector3Message dir_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.Vector3Message Dir {
      get { return dir_; }
      set {
        dir_ = value;
      }
    }

    /// <summary>Field number for the "elementType" field.</summary>
    public const int ElementTypeFieldNumber = 4;
    private int elementType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ElementType {
      get { return elementType_; }
      set {
        elementType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WallShootHitMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WallShootHitMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WallId != other.WallId) return false;
      if (!object.Equals(Origin, other.Origin)) return false;
      if (!object.Equals(Dir, other.Dir)) return false;
      if (ElementType != other.ElementType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WallId != 0) hash ^= WallId.GetHashCode();
      if (origin_ != null) hash ^= Origin.GetHashCode();
      if (dir_ != null) hash ^= Dir.GetHashCode();
      if (ElementType != 0) hash ^= ElementType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WallId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WallId);
      }
      if (origin_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Origin);
      }
      if (dir_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Dir);
      }
      if (ElementType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ElementType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WallId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WallId);
      }
      if (origin_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Origin);
      }
      if (dir_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Dir);
      }
      if (ElementType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ElementType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WallId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WallId);
      }
      if (origin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Origin);
      }
      if (dir_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Dir);
      }
      if (ElementType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ElementType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WallShootHitMessage other) {
      if (other == null) {
        return;
      }
      if (other.WallId != 0) {
        WallId = other.WallId;
      }
      if (other.origin_ != null) {
        if (origin_ == null) {
          Origin = new global::Message.Vector3Message();
        }
        Origin.MergeFrom(other.Origin);
      }
      if (other.dir_ != null) {
        if (dir_ == null) {
          Dir = new global::Message.Vector3Message();
        }
        Dir.MergeFrom(other.Dir);
      }
      if (other.ElementType != 0) {
        ElementType = other.ElementType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WallId = input.ReadInt32();
            break;
          }
          case 18: {
            if (origin_ == null) {
              Origin = new global::Message.Vector3Message();
            }
            input.ReadMessage(Origin);
            break;
          }
          case 26: {
            if (dir_ == null) {
              Dir = new global::Message.Vector3Message();
            }
            input.ReadMessage(Dir);
            break;
          }
          case 32: {
            ElementType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            WallId = input.ReadInt32();
            break;
          }
          case 18: {
            if (origin_ == null) {
              Origin = new global::Message.Vector3Message();
            }
            input.ReadMessage(Origin);
            break;
          }
          case 26: {
            if (dir_ == null) {
              Dir = new global::Message.Vector3Message();
            }
            input.ReadMessage(Dir);
            break;
          }
          case 32: {
            ElementType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
