// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AreaElementDamageMes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from AreaElementDamageMes.proto</summary>
  public static partial class AreaElementDamageMesReflection {

    #region Descriptor
    /// <summary>File descriptor for AreaElementDamageMes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AreaElementDamageMesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpBcmVhRWxlbWVudERhbWFnZU1lcy5wcm90bxIHTWVzc2FnZRoUVmVjdG9y",
            "M01lc3NhZ2UucHJvdG8aGkVsZW1lbnRBdHRhY2tNZXNzYWdlLnByb3RvIuMB",
            "ChRBcmVhRWxlbWVudERhbWFnZU1lcxInCgZjZW50ZXIYASABKAsyFy5NZXNz",
            "YWdlLlZlY3RvcjNNZXNzYWdlEg4KBnJhZGl1cxgCIAEoAhI0Cg1lbGVtZW50",
            "QXR0YWNrGAMgAygLMh0uTWVzc2FnZS5FbGVtZW50QXR0YWNrTWVzc2FnZRI2",
            "Cgdhb2VUeXBlGAQgASgOMiUuTWVzc2FnZS5BcmVhRWxlbWVudERhbWFnZU1l",
            "cy5BT0VUeXBlIiQKB0FPRVR5cGUSCgoGTm9ybWFsEAASDQoJRXhwbG9zaW9u",
            "EAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.Vector3MessageReflection.Descriptor, global::Message.ElementAttackMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.AreaElementDamageMes), global::Message.AreaElementDamageMes.Parser, new[]{ "Center", "Radius", "ElementAttack", "AoeType" }, null, new[]{ typeof(global::Message.AreaElementDamageMes.Types.AOEType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AreaElementDamageMes : pb::IMessage<AreaElementDamageMes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AreaElementDamageMes> _parser = new pb::MessageParser<AreaElementDamageMes>(() => new AreaElementDamageMes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AreaElementDamageMes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.AreaElementDamageMesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AreaElementDamageMes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AreaElementDamageMes(AreaElementDamageMes other) : this() {
      center_ = other.center_ != null ? other.center_.Clone() : null;
      radius_ = other.radius_;
      elementAttack_ = other.elementAttack_.Clone();
      aoeType_ = other.aoeType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AreaElementDamageMes Clone() {
      return new AreaElementDamageMes(this);
    }

    /// <summary>Field number for the "center" field.</summary>
    public const int CenterFieldNumber = 1;
    private global::Message.Vector3Message center_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.Vector3Message Center {
      get { return center_; }
      set {
        center_ = value;
      }
    }

    /// <summary>Field number for the "radius" field.</summary>
    public const int RadiusFieldNumber = 2;
    private float radius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Radius {
      get { return radius_; }
      set {
        radius_ = value;
      }
    }

    /// <summary>Field number for the "elementAttack" field.</summary>
    public const int ElementAttackFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Message.ElementAttackMessage> _repeated_elementAttack_codec
        = pb::FieldCodec.ForMessage(26, global::Message.ElementAttackMessage.Parser);
    private readonly pbc::RepeatedField<global::Message.ElementAttackMessage> elementAttack_ = new pbc::RepeatedField<global::Message.ElementAttackMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Message.ElementAttackMessage> ElementAttack {
      get { return elementAttack_; }
    }

    /// <summary>Field number for the "aoeType" field.</summary>
    public const int AoeTypeFieldNumber = 4;
    private global::Message.AreaElementDamageMes.Types.AOEType aoeType_ = global::Message.AreaElementDamageMes.Types.AOEType.Normal;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.AreaElementDamageMes.Types.AOEType AoeType {
      get { return aoeType_; }
      set {
        aoeType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AreaElementDamageMes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AreaElementDamageMes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Center, other.Center)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Radius, other.Radius)) return false;
      if(!elementAttack_.Equals(other.elementAttack_)) return false;
      if (AoeType != other.AoeType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (center_ != null) hash ^= Center.GetHashCode();
      if (Radius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Radius);
      hash ^= elementAttack_.GetHashCode();
      if (AoeType != global::Message.AreaElementDamageMes.Types.AOEType.Normal) hash ^= AoeType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (center_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Center);
      }
      if (Radius != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Radius);
      }
      elementAttack_.WriteTo(output, _repeated_elementAttack_codec);
      if (AoeType != global::Message.AreaElementDamageMes.Types.AOEType.Normal) {
        output.WriteRawTag(32);
        output.WriteEnum((int) AoeType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (center_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Center);
      }
      if (Radius != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Radius);
      }
      elementAttack_.WriteTo(ref output, _repeated_elementAttack_codec);
      if (AoeType != global::Message.AreaElementDamageMes.Types.AOEType.Normal) {
        output.WriteRawTag(32);
        output.WriteEnum((int) AoeType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (center_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Center);
      }
      if (Radius != 0F) {
        size += 1 + 4;
      }
      size += elementAttack_.CalculateSize(_repeated_elementAttack_codec);
      if (AoeType != global::Message.AreaElementDamageMes.Types.AOEType.Normal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AoeType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AreaElementDamageMes other) {
      if (other == null) {
        return;
      }
      if (other.center_ != null) {
        if (center_ == null) {
          Center = new global::Message.Vector3Message();
        }
        Center.MergeFrom(other.Center);
      }
      if (other.Radius != 0F) {
        Radius = other.Radius;
      }
      elementAttack_.Add(other.elementAttack_);
      if (other.AoeType != global::Message.AreaElementDamageMes.Types.AOEType.Normal) {
        AoeType = other.AoeType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (center_ == null) {
              Center = new global::Message.Vector3Message();
            }
            input.ReadMessage(Center);
            break;
          }
          case 21: {
            Radius = input.ReadFloat();
            break;
          }
          case 26: {
            elementAttack_.AddEntriesFrom(input, _repeated_elementAttack_codec);
            break;
          }
          case 32: {
            AoeType = (global::Message.AreaElementDamageMes.Types.AOEType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (center_ == null) {
              Center = new global::Message.Vector3Message();
            }
            input.ReadMessage(Center);
            break;
          }
          case 21: {
            Radius = input.ReadFloat();
            break;
          }
          case 26: {
            elementAttack_.AddEntriesFrom(ref input, _repeated_elementAttack_codec);
            break;
          }
          case 32: {
            AoeType = (global::Message.AreaElementDamageMes.Types.AOEType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AreaElementDamageMes message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum AOEType {
        [pbr::OriginalName("Normal")] Normal = 0,
        [pbr::OriginalName("Explosion")] Explosion = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
