// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DynamicItemHitMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from DynamicItemHitMessage.proto</summary>
  public static partial class DynamicItemHitMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for DynamicItemHitMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DynamicItemHitMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtEeW5hbWljSXRlbUhpdE1lc3NhZ2UucHJvdG8SB01lc3NhZ2UaGkVsZW1l",
            "bnRBdHRhY2tNZXNzYWdlLnByb3RvIoABChVEeW5hbWljSXRlbUhpdE1lc3Nh",
            "Z2USGwoTY2xpZW50RHluYW1pY0l0ZW1JZBgBIAEoBRIUCgxmcm9tUGxheWVy",
            "SWQYAiABKAUSNAoNZWxlbWVudEF0dGFjaxgDIAEoCzIdLk1lc3NhZ2UuRWxl",
            "bWVudEF0dGFja01lc3NhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.ElementAttackMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.DynamicItemHitMessage), global::Message.DynamicItemHitMessage.Parser, new[]{ "ClientDynamicItemId", "FromPlayerId", "ElementAttack" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 动态物体受攻击消息，S -> C
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DynamicItemHitMessage : pb::IMessage<DynamicItemHitMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DynamicItemHitMessage> _parser = new pb::MessageParser<DynamicItemHitMessage>(() => new DynamicItemHitMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DynamicItemHitMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.DynamicItemHitMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicItemHitMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicItemHitMessage(DynamicItemHitMessage other) : this() {
      clientDynamicItemId_ = other.clientDynamicItemId_;
      fromPlayerId_ = other.fromPlayerId_;
      elementAttack_ = other.elementAttack_ != null ? other.elementAttack_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicItemHitMessage Clone() {
      return new DynamicItemHitMessage(this);
    }

    /// <summary>Field number for the "clientDynamicItemId" field.</summary>
    public const int ClientDynamicItemIdFieldNumber = 1;
    private int clientDynamicItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ClientDynamicItemId {
      get { return clientDynamicItemId_; }
      set {
        clientDynamicItemId_ = value;
      }
    }

    /// <summary>Field number for the "fromPlayerId" field.</summary>
    public const int FromPlayerIdFieldNumber = 2;
    private int fromPlayerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FromPlayerId {
      get { return fromPlayerId_; }
      set {
        fromPlayerId_ = value;
      }
    }

    /// <summary>Field number for the "elementAttack" field.</summary>
    public const int ElementAttackFieldNumber = 3;
    private global::Message.ElementAttackMessage elementAttack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.ElementAttackMessage ElementAttack {
      get { return elementAttack_; }
      set {
        elementAttack_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DynamicItemHitMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DynamicItemHitMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientDynamicItemId != other.ClientDynamicItemId) return false;
      if (FromPlayerId != other.FromPlayerId) return false;
      if (!object.Equals(ElementAttack, other.ElementAttack)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientDynamicItemId != 0) hash ^= ClientDynamicItemId.GetHashCode();
      if (FromPlayerId != 0) hash ^= FromPlayerId.GetHashCode();
      if (elementAttack_ != null) hash ^= ElementAttack.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientDynamicItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ClientDynamicItemId);
      }
      if (FromPlayerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FromPlayerId);
      }
      if (elementAttack_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ElementAttack);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientDynamicItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ClientDynamicItemId);
      }
      if (FromPlayerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FromPlayerId);
      }
      if (elementAttack_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ElementAttack);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientDynamicItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientDynamicItemId);
      }
      if (FromPlayerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromPlayerId);
      }
      if (elementAttack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElementAttack);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DynamicItemHitMessage other) {
      if (other == null) {
        return;
      }
      if (other.ClientDynamicItemId != 0) {
        ClientDynamicItemId = other.ClientDynamicItemId;
      }
      if (other.FromPlayerId != 0) {
        FromPlayerId = other.FromPlayerId;
      }
      if (other.elementAttack_ != null) {
        if (elementAttack_ == null) {
          ElementAttack = new global::Message.ElementAttackMessage();
        }
        ElementAttack.MergeFrom(other.ElementAttack);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ClientDynamicItemId = input.ReadInt32();
            break;
          }
          case 16: {
            FromPlayerId = input.ReadInt32();
            break;
          }
          case 26: {
            if (elementAttack_ == null) {
              ElementAttack = new global::Message.ElementAttackMessage();
            }
            input.ReadMessage(ElementAttack);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ClientDynamicItemId = input.ReadInt32();
            break;
          }
          case 16: {
            FromPlayerId = input.ReadInt32();
            break;
          }
          case 26: {
            if (elementAttack_ == null) {
              ElementAttack = new global::Message.ElementAttackMessage();
            }
            input.ReadMessage(ElementAttack);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
