// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HyperBloomRequestMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from HyperBloomRequestMessage.proto</summary>
  public static partial class HyperBloomRequestMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for HyperBloomRequestMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HyperBloomRequestMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5IeXBlckJsb29tUmVxdWVzdE1lc3NhZ2UucHJvdG8SB01lc3NhZ2UaFFZl",
            "Y3RvcjNNZXNzYWdlLnByb3RvGhpFbGVtZW50QXR0YWNrTWVzc2FnZS5wcm90",
            "byK8AQoYSHlwZXJCbG9vbVJlcXVlc3RNZXNzYWdlEhsKE2NsaWVudER5bmFt",
            "aWNJdGVtSWQYASABKAUSFAoMbWFza1BsYXllcklkGAIgASgFEicKBmNlbnRl",
            "chgDIAEoCzIXLk1lc3NhZ2UuVmVjdG9yM01lc3NhZ2USDgoGcmFkaXVzGAQg",
            "ASgCEjQKDWVsZW1lbnRBdHRhY2sYBSABKAsyHS5NZXNzYWdlLkVsZW1lbnRB",
            "dHRhY2tNZXNzYWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.Vector3MessageReflection.Descriptor, global::Message.ElementAttackMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.HyperBloomRequestMessage), global::Message.HyperBloomRequestMessage.Parser, new[]{ "ClientDynamicItemId", "MaskPlayerId", "Center", "Radius", "ElementAttack" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 超绽放请求消息，C -> S
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HyperBloomRequestMessage : pb::IMessage<HyperBloomRequestMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HyperBloomRequestMessage> _parser = new pb::MessageParser<HyperBloomRequestMessage>(() => new HyperBloomRequestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HyperBloomRequestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.HyperBloomRequestMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HyperBloomRequestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HyperBloomRequestMessage(HyperBloomRequestMessage other) : this() {
      clientDynamicItemId_ = other.clientDynamicItemId_;
      maskPlayerId_ = other.maskPlayerId_;
      center_ = other.center_ != null ? other.center_.Clone() : null;
      radius_ = other.radius_;
      elementAttack_ = other.elementAttack_ != null ? other.elementAttack_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HyperBloomRequestMessage Clone() {
      return new HyperBloomRequestMessage(this);
    }

    /// <summary>Field number for the "clientDynamicItemId" field.</summary>
    public const int ClientDynamicItemIdFieldNumber = 1;
    private int clientDynamicItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ClientDynamicItemId {
      get { return clientDynamicItemId_; }
      set {
        clientDynamicItemId_ = value;
      }
    }

    /// <summary>Field number for the "maskPlayerId" field.</summary>
    public const int MaskPlayerIdFieldNumber = 2;
    private int maskPlayerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaskPlayerId {
      get { return maskPlayerId_; }
      set {
        maskPlayerId_ = value;
      }
    }

    /// <summary>Field number for the "center" field.</summary>
    public const int CenterFieldNumber = 3;
    private global::Message.Vector3Message center_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.Vector3Message Center {
      get { return center_; }
      set {
        center_ = value;
      }
    }

    /// <summary>Field number for the "radius" field.</summary>
    public const int RadiusFieldNumber = 4;
    private float radius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Radius {
      get { return radius_; }
      set {
        radius_ = value;
      }
    }

    /// <summary>Field number for the "elementAttack" field.</summary>
    public const int ElementAttackFieldNumber = 5;
    private global::Message.ElementAttackMessage elementAttack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Message.ElementAttackMessage ElementAttack {
      get { return elementAttack_; }
      set {
        elementAttack_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HyperBloomRequestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HyperBloomRequestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientDynamicItemId != other.ClientDynamicItemId) return false;
      if (MaskPlayerId != other.MaskPlayerId) return false;
      if (!object.Equals(Center, other.Center)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Radius, other.Radius)) return false;
      if (!object.Equals(ElementAttack, other.ElementAttack)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientDynamicItemId != 0) hash ^= ClientDynamicItemId.GetHashCode();
      if (MaskPlayerId != 0) hash ^= MaskPlayerId.GetHashCode();
      if (center_ != null) hash ^= Center.GetHashCode();
      if (Radius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Radius);
      if (elementAttack_ != null) hash ^= ElementAttack.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientDynamicItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ClientDynamicItemId);
      }
      if (MaskPlayerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MaskPlayerId);
      }
      if (center_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Center);
      }
      if (Radius != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Radius);
      }
      if (elementAttack_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ElementAttack);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientDynamicItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ClientDynamicItemId);
      }
      if (MaskPlayerId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MaskPlayerId);
      }
      if (center_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Center);
      }
      if (Radius != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Radius);
      }
      if (elementAttack_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ElementAttack);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientDynamicItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientDynamicItemId);
      }
      if (MaskPlayerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaskPlayerId);
      }
      if (center_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Center);
      }
      if (Radius != 0F) {
        size += 1 + 4;
      }
      if (elementAttack_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ElementAttack);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HyperBloomRequestMessage other) {
      if (other == null) {
        return;
      }
      if (other.ClientDynamicItemId != 0) {
        ClientDynamicItemId = other.ClientDynamicItemId;
      }
      if (other.MaskPlayerId != 0) {
        MaskPlayerId = other.MaskPlayerId;
      }
      if (other.center_ != null) {
        if (center_ == null) {
          Center = new global::Message.Vector3Message();
        }
        Center.MergeFrom(other.Center);
      }
      if (other.Radius != 0F) {
        Radius = other.Radius;
      }
      if (other.elementAttack_ != null) {
        if (elementAttack_ == null) {
          ElementAttack = new global::Message.ElementAttackMessage();
        }
        ElementAttack.MergeFrom(other.ElementAttack);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ClientDynamicItemId = input.ReadInt32();
            break;
          }
          case 16: {
            MaskPlayerId = input.ReadInt32();
            break;
          }
          case 26: {
            if (center_ == null) {
              Center = new global::Message.Vector3Message();
            }
            input.ReadMessage(Center);
            break;
          }
          case 37: {
            Radius = input.ReadFloat();
            break;
          }
          case 42: {
            if (elementAttack_ == null) {
              ElementAttack = new global::Message.ElementAttackMessage();
            }
            input.ReadMessage(ElementAttack);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ClientDynamicItemId = input.ReadInt32();
            break;
          }
          case 16: {
            MaskPlayerId = input.ReadInt32();
            break;
          }
          case 26: {
            if (center_ == null) {
              Center = new global::Message.Vector3Message();
            }
            input.ReadMessage(Center);
            break;
          }
          case 37: {
            Radius = input.ReadFloat();
            break;
          }
          case 42: {
            if (elementAttack_ == null) {
              ElementAttack = new global::Message.ElementAttackMessage();
            }
            input.ReadMessage(ElementAttack);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
